# install nginx
# depends on: none
#

- name: Install nginx
  apt: pkg=nginx state=present

# copy sites-available

- copy:
    src: "../templates/nginx/sites-available/paulfearn.duckdns.org"
    dest: "/etc/nginx/sites-available/paulfearn.duckdns.org"

# create site-enabled from sites-available


- file:
    src: "/etc/nginx/sites-available/paulfearn.duckdns.org"
    dest: "/etc/nginx/sites-enabled/paulfearn.duckdns.org"
    state: link

# add any additional fields required to nginx.conf