# install git: sudo apt-get install git-core
# depends on: none
#

# install git:
- name: Install git
  apt: pkg=git-core state=present

- git:
    repo: 'https://{{ git_user }}:{{ git_pass }}@pfgit.duckdns.org/repos/web/blog.git'
    dest: /usr/share/nginx/html/tinklr
    version: release