# Ansible Playbook for my current home desktop computer running SolusOS
# 
# ansible-playbook -i ~/ansible/hosts /playbooks/solus-desktop.yml
---
- hosts: solus
  gather_facts: yes
  vars_prompt:

  - name: username
    prompt: "please enter your unix username:"
    private: no

  tasks:
  
    # Development
    - name: Install Git
      become: yes
      command: eopkg install git

    - name: Enable colors in git output
      become: yes
      command: git config --global color.ui auto

    - name: Install VS Code
      become: yes
      command: eopkg install vscode

    - name: Install Terminator
      become: yes
      command: eopkg install terminator

    - name: Install Angry IP Scanner
      become: yes
      command: eopkg install ipscan

    - name: Install system.devel
      become: yes
      command: eopkg install -c system.devel

    - name: Upgrade all the things
      become: yes
      command: eopkg upgrade

    # Media
    - name: Install Cheese Photo Booth
      become: yes
      command: eopkg install cheese

    - name: Install The Gimp
      become: yes
      command: eopkg install gimp

    - name: Install gLabels
      become: yes
      command: eopkg install glabels

    # Electronics and 3D Printing
    - name: Install LibreCad
      become: yes
      command: eopkg install librecad

    - name: Install Fritzing
      become: yes
      command: eopkg install fritzing

    # Utility
    - name: Install Deja Dup
      become: yes
      command: eopkg install deja-dup

    - name: Install htop
      become: yes
      command: eopkg install htop

    - name: Install Synergy
      become: yes
      command: eopkg install synergy

    # Third Party Software
    - name: Download Microsoft fonts spec
      become: yes
      command: eopkg bi --ignore-safety https://raw.githubusercontent.com/solus-project/3rd-party/master/desktop/font/mscorefonts/pspec.xml
    - name: Install Microsoft fonts
      become: yes
      command: eopkg it mscorefonts*.eopkg
      ignore_errors: yes

    - name: Download Google Chrome spec
      become: yes
      command: eopkg bi --ignore-safety https://raw.githubusercontent.com/solus-project/3rd-party/master/network/web/browser/google-chrome-stable/pspec.xml
    - name: Install Google Chrome
      become: yes
      command: eopkg it google-chrome-*.eopkg
      ignore_errors: yes

    - name: Download Skype for Linux spec
      become: yes
      command: eopkg bi --ignore-safety https://raw.githubusercontent.com/solus-project/3rd-party/master/network/im/skype/pspec.xml

    - name: Install Skype for Linux
      become: yes
      command: eopkg it skype*.eopkg
      ignore_errors: yes

    #### Manual Installations ####
    # Arduino IDE
    # Create a folder
    - name: Creates directory
      file: path=/home/{{ username }}/Downloads/Arduino-1.8.4 state=directory
    # Download and Extract
    - unarchive:
        src: https://github.com/arduino/Arduino/releases/download/1.8.4/Arduino-1.8.4.tar.xz
        dest: /home/{{ username }}/Downloads
        remote_src: True
    # Install
    - name: Run Arduino IDE install file
      become: yes
      command: /home/{{ username }}/Downloads/Arduino-1.8.4/build/linux/dist/install.sh

    # Download the latest version of the Dymo LabelMaker 450 Drivers using git
    - name: Git clone Dymo LabelMaker 450 Drivers
      git:
        repo: "https://aur.archlinux.org/dymo-cups-drivers.git"
        dest: "/home/{{ username }}/Downloads/dymo-cups-drivers"
        update: yes
    # ./configure
    - name: configure
      become: yes
      command: ./configure
      args:
        chdir: "/home/{{ username }}/Downloads/dymo-cups-drivers"
    # make
    - name: make
      become: yes
      command: make
      args:
        chdir: "/home/{{ username }}/Downloads/dymo-cups-drivers"
    # make install
    - name: make install
      become: yes
      command: make install
      args:
        chdir: "/home/{{ username }}/Downloads/dymo-cups-drivers"
      # Wish List
      # Arduino IDE
      # Cura
      # SLi3r Prusa Editions
      # Simplify 3D


  handlers:

    - include: ../handlers/reboot.yml
      tags: system

  
